Documents/ChampSupermarket/ChampSupermarket/Models/Suplier.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ChampSupermarket.Models
{
    public class Suplier
    {
        public int SuplierID { get; set; }
        public String SuplierName { get; set; }
        public String Adress { get; set; }
        public int Phone { get; set; }

        public virtual ICollection<Product> ProductsSuplier { get; set; }
    }
}

Documents/ChampSupermarket/ChampSupermarket/Controllers/SuplierController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ChampSupermarket.Models;
using ChampSupermarket.DAL;
using PagedList;

namespace ChampSupermarket.Controllers
{
    public class SuplierController : Controller
    {
        private SupermarketContext db = new SupermarketContext();

        // GET: /Suplier/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.IDSortParm = String.IsNullOrEmpty(sortOrder) ? "Phone_desc" : "";
            //ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var supliers = from s in db.supliers
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                supliers = supliers.Where(s => s.SuplierName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    supliers = supliers.OrderByDescending(s => s.SuplierName);
                    break;
                case "Phone_desc":
                    supliers = supliers.OrderBy(s => s.Phone);
                    break;
               /* case "date_desc":
                    supliers = supliers.OrderByDescending(s => s.);
                    break;*/
                default:
                    supliers = supliers.OrderBy(s => s.SuplierID);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(supliers.ToPagedList(pageNumber, pageSize));
        }

        // GET: /Suplier/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Suplier suplier = db.supliers.Find(id);
            if (suplier == null)
            {
                return HttpNotFound();
            }
            return View(suplier);
        }

        // GET: /Suplier/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Suplier/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="SuplierID,SuplierName,Adress,Phone")] Suplier suplier)
        {
            if (ModelState.IsValid)
            {
                db.supliers.Add(suplier);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(suplier);
        }

        // GET: /Suplier/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Suplier suplier = db.supliers.Find(id);
            if (suplier == null)
            {
                return HttpNotFound();
            }
            return View(suplier);
        }

        // POST: /Suplier/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="SuplierID,SuplierName,Adress,Phone")] Suplier suplier)
        {
            if (ModelState.IsValid)
            {
                db.Entry(suplier).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(suplier);
        }

        // GET: /Suplier/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Suplier suplier = db.supliers.Find(id);
            if (suplier == null)
            {
                return HttpNotFound();
            }
            return View(suplier);
        }

        // POST: /Suplier/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Suplier suplier = db.supliers.Find(id);
            db.supliers.Remove(suplier);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Documents/ChampSupermarket/ChampSupermarket/Views/Suplier/Create.cshtml
@model ChampSupermarket.Models.Suplier

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Suplier</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.SuplierName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SuplierName)
                @Html.ValidationMessageFor(model => model.SuplierName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adress, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adress)
                @Html.ValidationMessageFor(model => model.Adress)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone)
                @Html.ValidationMessageFor(model => model.Phone)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Documents/ChampSupermarket/ChampSupermarket/Views/Suplier/Delete.cshtml
@model ChampSupermarket.Models.Suplier

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Suplier</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SuplierName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SuplierName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Documents/ChampSupermarket/ChampSupermarket/Views/Suplier/Details.cshtml
@model ChampSupermarket.Models.Suplier

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Suplier</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SuplierName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SuplierName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProductsSuplier)
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Product ID</th>
                    <th>Name Product</th>
                </tr>
                @foreach (var item in Model.ProductsSuplier)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProductID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NameProduct)
                        </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SuplierID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Documents/ChampSupermarket/ChampSupermarket/Views/Suplier/Edit.cshtml
@model ChampSupermarket.Models.Suplier

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Suplier</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.SuplierID)

        <div class="form-group">
            @Html.LabelFor(model => model.SuplierName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SuplierName)
                @Html.ValidationMessageFor(model => model.SuplierName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adress, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adress)
                @Html.ValidationMessageFor(model => model.Adress)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone)
                @Html.ValidationMessageFor(model => model.Phone)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Documents/ChampSupermarket/ChampSupermarket/Views/Suplier/Index.cshtml
@model PagedList.IPagedList<ChampSupermarket.Models.Suplier>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Supliers";
}

<h2>Supliers</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Suplier", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
  
    <tr>
        <th>
            @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm,currentFilter=ViewBag.CurrentFilter })
        </th>
        <th>
           
            Adress
        </th>
        <th>
            @Html.ActionLink("Phone", "Index", new { sortOrder = ViewBag.PhoneSortParm,currentFilter=ViewBag.CurrentFilter})
        </th>
        <th></th>
    </tr>


@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SuplierName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Adress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.SuplierID }) |
            @Html.ActionLink("Details", "Details", new { id=item.SuplierID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.SuplierID })
        </td>
    </tr>
}

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))